### PR TITLE
Proposed fix for change in heroku deployments regarding recent changes:

### PR DESCRIPTION
**Pull request by cybervitor**
https://devcenter.heroku.com/changelog-items/2035

### CODE REVIEW

**Review by dleandro — COMMENTED** [review]
Which dbms do you guys use?

**Review by dleandro — CHANGES_REQUESTED** [review]
The require ssl and rejectUnauthorized flags need to use environment variables.
If not it might break something for other users

**Comment by cybervitor** [comment]
> Which dbms do you guys use?

We're using Postgres, and sure, we could change the ssl and rejectUnauthorized to environment variables, it would just be nice if these new environment variables would be added to the documentation of the project.

Yes you are right i will try to do that in the near future

**Review by dleandro — APPROVED** [review]

**Comment by cybervitor** [comment]
So, since this was approved, could someone merge this? :)

**Comment by dleandro** [comment]
Sorry i forgot you can’t merge it

**Comment by cybervitor** [comment]
Also, it would be nice if you could make this avaliable through the npm package? 
We've tried updating yet it does not get the most recent version of the code.

**Pull request merged**
